version: '3'

services:
  football_players_airflow:
    image: football_players_airflow:latest

    volumes:
      - ./airflow:/opt/airflow

    ports:
      - "8080:8080"

    command: airflow standalone
